<?php require 'templates/header.phtml' ?>
<div class="colorFondo">
<h2>Modificar Vino</h2>
<form action="enviarModificarVino/<?= $id ?>" method="POST">


    <label for="nombre" class="form-label">Nombre</label>
    <input type="text" name="Nombre" placeholder=<?= $vino->Nombre ?>>
    <label for="nombre" class="form-label">Tipo</label>
    <input type="text" name="Tipo" placeholder=<?= $vino->Tipo ?>>
    <label for="nombre" class="form-label">Azucar</label>
    <input type="text" name="Azucar" placeholder=<?= $vino->Azucar ?>>

    <label for="nombre" class="form-label">Bodega</label>
    <select name="id_bodega" placeholder=<?= $vino->Nombre_bodega ?>>
        <?php foreach ($bodegas as $bodega) : ?>
            <option value=<?= $bodega->id_bodega ?>><?= $bodega->Nombre_bodega ?></option>
        <?php endforeach ?>
    </select>
    <label for="nombre" class="form-label">Cepa</label>
    <select name="id_cepa" placeholder=<?= $vino->Nombre_cepa ?>>
        <?php foreach ($cepas as $cepa) : ?>
            <option value=<?= $cepa->id_cepa ?>><?= $cepa->Nombre_cepa ?></option>
        <?php endforeach ?>
    </select>


    <button type="submit">Modicar</button>
</form>
</div>

<?php require 'templates/footer.phtml' ?>