<?php require 'templates/header.phtml' ?>
<div class="colorFondo">
<h1>Vinos por bodega: <?= $bodega->Nombre_bodega ?></h1>
    <table class="table table-success table-striped">
    <td class="table-secondary">Vino</td>
    <td class="table-secondary">Cepa</td>
        <?php foreach ($vinos as $vino) : ?>
            <tr>
                <td class="table-secondary"><a href="mostrarVino/<?= $vino->ID_vino ?>"> <?= $vino->Nombre ?> </a></td>
                <td class="table-secondary"><a href="mostrarCepa/<?= $vino->id_cepa ?>"><?= $vino->Nombre_cepa ?></a></td>
            </tr>
        <?php endforeach ?>
    </table>
</div>
<?php require 'templates/footer.phtml' ?>